package com.vuog.telebotmanager.infrastructure.util;

import com.vuog.telebotmanager.domain.entity.BotPlugin;
import com.vuog.telebotmanager.domain.service.PluginManager;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

/**
 * Utility class for botPlugin operations
 * Provides helper methods for botPlugin management and execution
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class PluginUtils {

    private final PluginManager pluginManager;

    /**
     * Check if a botPlugin is available for execution
     */
    public boolean isPluginAvailable(String pluginName) {
        try {
            return pluginManager.isPluginLoaded(pluginName);
        } catch (Exception e) {
            log.error("Error checking botPlugin availability: {}", pluginName, e);
            return false;
        }
    }

    /**
     * Get botPlugin information
     */
    public Optional<BotPlugin> getPluginInfo(String pluginName) {
        try {
            return pluginManager.getPluginByName(pluginName);
        } catch (Exception e) {
            log.error("Error getting botPlugin info: {}", pluginName, e);
            return Optional.empty();
        }
    }

    /**
     * Get all loaded botPlugins
     */
    public List<BotPlugin> getLoadedPlugins() {
        try {
            return pluginManager.getLoadedPlugins();
        } catch (Exception e) {
            log.error("Error getting loaded botPlugins", e);
            return List.of();
        }
    }

    /**
     * Get botPlugin statistics
     */
    public PluginManager.PluginExecutionStats getPluginStats(String pluginName) {
        try {
            return pluginManager.getPluginStats(pluginName);
        } catch (Exception e) {
            log.error("Error getting botPlugin stats: {}", pluginName, e);
            return null;
        }
    }

    /**
     * Validate botPlugin source code
     */
    public boolean validatePluginSource(String sourceCode) {
        if (sourceCode == null || sourceCode.trim().isEmpty()) {
            return false;
        }

        // Basic validation - check for required elements
        return sourceCode.contains("public class") &&
                sourceCode.contains("public") &&
                sourceCode.contains("String");
    }

    /**
     * Extract class name from source code
     */
    public String extractClassName(String sourceCode) {
        if (sourceCode == null || sourceCode.trim().isEmpty()) {
            return null;
        }

        try {
            // Simple regex to extract class name
            String[] lines = sourceCode.split("\n");
            for (String line : lines) {
                if (line.trim().startsWith("public class")) {
                    String[] parts = line.trim().split("\\s+");
                    if (parts.length >= 3) {
                        return parts[2].split("\\{")[0].trim();
                    }
                }
            }
        } catch (Exception e) {
            log.error("Error extracting class name from source code", e);
        }

        return null;
    }

    /**
     * Extract method name from source code
     */
    public String extractMethodName(String sourceCode) {
        if (sourceCode == null || sourceCode.trim().isEmpty()) {
            return null;
        }

        try {
            // Simple regex to extract method name
            String[] lines = sourceCode.split("\n");
            for (String line : lines) {
                if (line.trim().startsWith("public String") || line.trim().startsWith("public Object")) {
                    String[] parts = line.trim().split("\\s+");
                    if (parts.length >= 3) {
                        String methodPart = parts[2].split("\\(")[0].trim();
                        return methodPart;
                    }
                }
            }
        } catch (Exception e) {
            log.error("Error extracting method name from source code", e);
        }

        return null;
    }

    /**
     * Create a simple botPlugin template
     */
    public String createPluginTemplate(String className, String methodName) {
        return String.format("""
                package com.vuog.telebotmanager.botPlugins;
                
                import java.util.Map;
                
                /**
                 * Custom botPlugin: %s
                 * Generated by Telegram Bot Manager
                 */
                public class %s {
                
                    /**
                     * Plugin method: %s
                     * @param input Input data
                     * @param parameters Plugin parameters
                     * @return Plugin result
                     */
                    public String %s(String input, Map<String, Object> parameters) {
                        // TODO: Implement your botPlugin logic here
                
                        // Example implementation
                        return "Hello from botPlugin: " + input;
                    }
                }
                """, className, className, methodName, methodName);
    }

    /**
     * Create a botPlugin template for AI processing
     */
    public String createAiPluginTemplate(String className, String methodName) {
        return String.format("""
                package com.vuog.telebotmanager.botPlugins;
                
                import java.util.Map;
                
                /**
                 * AI Plugin: %s
                 * Generated by Telegram Bot Manager
                 */
                public class %s {
                
                    /**
                     * AI processing method: %s
                     * @param input Input text
                     * @param parameters AI parameters
                     * @return AI processed result
                     */
                    public String %s(String input, Map<String, Object> parameters) {
                        // TODO: Implement AI processing logic here
                
                        // Example AI processing
                        return "AI processed: " + input;
                    }
                }
                """, className, className, methodName, methodName);
    }

    /**
     * Create a botPlugin template for data transformation
     */
    public String createDataTransformPluginTemplate(String className, String methodName) {
        return String.format("""
                package com.vuog.telebotmanager.botPlugins;
                
                import java.util.Map;
                
                /**
                 * Data Transform Plugin: %s
                 * Generated by Telegram Bot Manager
                 */
                public class %s {
                
                    /**
                     * Data transformation method: %s
                     * @param input Input data
                     * @param parameters Transform parameters
                     * @return Transformed data
                     */
                    public String %s(String input, Map<String, Object> parameters) {
                        // TODO: Implement data transformation logic here
                
                        // Example transformation
                        return input.toUpperCase();
                    }
                }
                """, className, className, methodName, methodName);
    }

    /**
     * Get botPlugin execution summary
     */
    public String getPluginExecutionSummary(String pluginName) {
        PluginManager.PluginExecutionStats stats = getPluginStats(pluginName);
        if (stats == null) {
            return "No statistics available for botPlugin: " + pluginName;
        }

        return String.format("""
                        📊 <b>Plugin Statistics: %s</b>
                        
                        <b>Executions:</b> %d
                        <b>Success Rate:</b> %.1f%%
                        <b>Average Time:</b> %.2f ms
                        <b>Last Execution:</b> %d ms ago
                        
                        <b>Success:</b> %d
                        <b>Errors:</b> %d
                        """,
                pluginName,
                stats.getExecutionCount(),
                stats.getExecutionCount() > 0 ? (double) stats.getSuccessCount() / stats.getExecutionCount() * 100 : 0.0,
                stats.getAverageExecutionTime(),
                stats.getLastExecutionTime(),
                stats.getSuccessCount(),
                stats.getErrorCount());
    }

    /**
     * Format botPlugin list for display
     */
    public String formatPluginList(List<BotPlugin> botPlugins) {
        if (botPlugins == null || botPlugins.isEmpty()) {
            return "No botPlugins loaded";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("🔌 <b>Loaded Plugins</b>\n\n");

        for (BotPlugin botPlugin : botPlugins) {
            sb.append(String.format("• <b>%s</b> (%s)\n", botPlugin.getName(), botPlugin.getStatus()));
            sb.append(String.format("  Type: %s | Version: %s\n", botPlugin.getType(), botPlugin.getVersion()));
            if (botPlugin.getDescription() != null && !botPlugin.getDescription().trim().isEmpty()) {
                sb.append(String.format("  Description: %s\n", botPlugin.getDescription()));
            }
            sb.append("\n");
        }

        return sb.toString();
    }
}
